DROP TABLE p5_member
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_member_seq	;

DROP TABLE p5_parts 
	CASCADE CONSTRAINTS;
DROP sequence p5_parts_seq;

DROP TABLE p5_computer 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_computer_seq;

DROP TABLE p5_assembly 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_assembly_seq;

DROP TABLE p5_assque 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_assque_seq;

DROP TABLE p5_point 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_point_seq;

DROP TABLE p5_order 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_order_seq;

DROP TABLE p5_request 
	CASCADE CONSTRAINTS;

DROP TABLE p5_pay 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_pay_seq;

DROP TABLE p5_as 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_as_seq;

DROP TABLE p5_mgr 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_mgr_seq;

DROP TABLE p5_review 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_review_seq;

DROP TABLE p5_revcomm 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_revcomm_seq;

DROP TABLE p5_question 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_question_seq;

DROP TABLE p5_quecomm 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_quecomm_seq;

DROP TABLE p5_notice 
	CASCADE CONSTRAINTS;
DROP SEQUENCE p5_notice_seq;